import { db } from "@/lib/db";

// The salon's real, live service menu (185 services across Beauty, Clinic,
// Facials, and SPA categories) — sourced from the physical price list and
// entered directly, not placeholder/demo data. Replaces the old starter
// catalog. Safe to run once on a fresh install; skips seeding if services
// already exist so it never duplicates or overwrites edits made in the app.
const REAL_CATALOG: { name: string; category: string; price: number }[] = [
  { name: 'AB Repair', category: 'Beauty', price: 3500.00 },
  { name: 'Accessories per Nail', category: 'Beauty', price: 200.00 },
  { name: 'Acrylic Removal', category: 'Beauty', price: 1000.00 },
  { name: 'Acrylics', category: 'Beauty', price: 4500.00 },
  { name: 'Arm Scalp Repair', category: 'Beauty', price: 4500.00 },
  { name: 'Ayuverdic', category: 'Beauty', price: 3500.00 },
  { name: 'Balayage Color', category: 'Beauty', price: 9000.00 },
  { name: 'Beautiful Beginning', category: 'Beauty', price: 3000.00 },
  { name: 'Bikini', category: 'Beauty', price: 2000.00 },
  { name: 'Blowdry Only', category: 'Beauty', price: 500.00 },
  { name: 'Braids Boho Extended', category: 'Beauty', price: 4500.00 },
  { name: 'Braids Long Boho', category: 'Beauty', price: 4000.00 },
  { name: 'Braids Mid Lines/Box', category: 'Beauty', price: 1000.00 },
  { name: 'Brazilian', category: 'Beauty', price: 3000.00 },
  { name: 'Brazilian & Vagacial', category: 'Beauty', price: 5000.00 },
  { name: 'Bride Maids Make Up', category: 'Beauty', price: 4000.00 },
  { name: 'Brush Blowdry Only', category: 'Beauty', price: 800.00 },
  { name: 'Butter Treatment', category: 'Beauty', price: 1500.00 },
  { name: 'Chin', category: 'Beauty', price: 500.00 },
  { name: 'Classic Glam', category: 'Beauty', price: 3500.00 },
  { name: 'Classic Lashes', category: 'Beauty', price: 3500.00 },
  { name: 'Cocktail Calta', category: 'Beauty', price: 2000.00 },
  { name: 'Copy Design Hands', category: 'Beauty', price: 1500.00 },
  { name: 'Copy Design Legs', category: 'Beauty', price: 1500.00 },
  { name: 'Covering Grey', category: 'Beauty', price: 4500.00 },
  { name: 'Custom Bridal Make Up', category: 'Beauty', price: 15000.00 },
  { name: 'Customized Treatment', category: 'Beauty', price: 6000.00 },
  { name: 'Cutting & Filing', category: 'Beauty', price: 500.00 },
  { name: 'Dark & Lovely', category: 'Beauty', price: 3000.00 },
  { name: 'Eman Bridal', category: 'Beauty', price: 15000.00 },
  { name: 'Eman Bridal Make Up', category: 'Beauty', price: 30000.00 },
  { name: 'Extention Hair Style', category: 'Beauty', price: 6500.00 },
  { name: 'Extention Undo', category: 'Beauty', price: 300.00 },
  { name: 'Eyebrow Shaping', category: 'Beauty', price: 500.00 },
  { name: 'Eyebrow Waxing', category: 'Beauty', price: 800.00 },
  { name: 'Eyebrows', category: 'Beauty', price: 500.00 },
  { name: 'Face Shaving', category: 'Beauty', price: 500.00 },
  { name: 'Flation Only', category: 'Beauty', price: 1000.00 },
  { name: 'Full Bikini', category: 'Beauty', price: 2500.00 },
  { name: 'Full Body Waxing', category: 'Beauty', price: 7500.00 },
  { name: 'Full Face Waxing', category: 'Beauty', price: 2000.00 },
  { name: 'Full Glam Halal', category: 'Beauty', price: 5000.00 },
  { name: 'Full Hands (Heena)', category: 'Beauty', price: 2500.00 },
  { name: 'Full Hands Waxing', category: 'Beauty', price: 1500.00 },
  { name: 'Full Head Trimming', category: 'Beauty', price: 500.00 },
  { name: 'Full Legs (Heena)', category: 'Beauty', price: 2500.00 },
  { name: 'Full Legs Waxing', category: 'Beauty', price: 2000.00 },
  { name: 'Full Mega Growth', category: 'Beauty', price: 4000.00 },
  { name: 'Full Mizani Retouch', category: 'Beauty', price: 9000.00 },
  { name: 'Full Olive Retouch', category: 'Beauty', price: 4000.00 },
  { name: 'Fusion Moisture', category: 'Beauty', price: 4500.00 },
  { name: 'Fusion Strengther', category: 'Beauty', price: 4500.00 },
  { name: 'Gel Polish', category: 'Beauty', price: 1000.00 },
  { name: 'Gen Anti-Dandruff', category: 'Beauty', price: 4500.00 },
  { name: 'Gen Repair', category: 'Beauty', price: 3500.00 },
  { name: 'Glam Bridal', category: 'Beauty', price: 10000.00 },
  { name: 'Hair Pearl', category: 'Beauty', price: 2500.00 },
  { name: 'Half Hands', category: 'Beauty', price: 1000.00 },
  { name: 'Half Legs', category: 'Beauty', price: 1000.00 },
  { name: 'Heena Fashion Hands', category: 'Beauty', price: 1000.00 },
  { name: 'Heena Fashion Legs', category: 'Beauty', price: 1000.00 },
  { name: 'Heena Kids', category: 'Beauty', price: 500.00 },
  { name: 'Heena Kids Under 8 Years', category: 'Beauty', price: 800.00 },
  { name: 'Heena Treatment', category: 'Beauty', price: 2000.00 },
  { name: 'Hydra Leave-Ins', category: 'Beauty', price: 1500.00 },
  { name: 'Hydrating Mask', category: 'Beauty', price: 3000.00 },
  { name: 'Iron Curls Only', category: 'Beauty', price: 1300.00 },
  { name: 'Keratin Long Hair', category: 'Beauty', price: 20000.00 },
  { name: 'Keratin Mid Hair', category: 'Beauty', price: 18000.00 },
  { name: 'Keratin Small Hair', category: 'Beauty', price: 15000.00 },
  { name: 'Keratin Xtra Long', category: 'Beauty', price: 25000.00 },
  { name: 'Kids Boho', category: 'Beauty', price: 3500.00 },
  { name: 'Kids Natural Treats', category: 'Beauty', price: 1500.00 },
  { name: 'Kids Scalp Treats', category: 'Beauty', price: 4000.00 },
  { name: 'Knotless', category: 'Beauty', price: 4500.00 },
  { name: 'Knotless Extended', category: 'Beauty', price: 4000.00 },
  { name: 'Lash Refill', category: 'Beauty', price: 2000.00 },
  { name: 'Lash Removal', category: 'Beauty', price: 1500.00 },
  { name: 'Lines/Box Braids', category: 'Beauty', price: 500.00 },
  { name: 'Mega Growth Only', category: 'Beauty', price: 3000.00 },
  { name: 'Mizani Retouch Only', category: 'Beauty', price: 6000.00 },
  { name: 'Moustache', category: 'Beauty', price: 500.00 },
  { name: 'Nail Artwork', category: 'Beauty', price: 1000.00 },
  { name: 'Natural Hair Style', category: 'Beauty', price: 3500.00 },
  { name: 'Neck Highlight', category: 'Beauty', price: 13000.00 },
  { name: 'Neck Long Full Color', category: 'Beauty', price: 8000.00 },
  { name: 'Normal Polish', category: 'Beauty', price: 500.00 },
  { name: 'Olive Retouch', category: 'Beauty', price: 2800.00 },
  { name: 'Overlay Removal', category: 'Beauty', price: 1000.00 },
  { name: 'Overlays on Nails', category: 'Beauty', price: 2000.00 },
  { name: 'Overlays on Tips', category: 'Beauty', price: 3000.00 },
  { name: 'Own Presson Nails', category: 'Beauty', price: 500.00 },
  { name: 'Presson Nails', category: 'Beauty', price: 1000.00 },
  { name: 'Protein Long Hair', category: 'Beauty', price: 18000.00 },
  { name: 'Protein Mid Hair', category: 'Beauty', price: 15000.00 },
  { name: 'Protein Short Hair', category: 'Beauty', price: 13000.00 },
  { name: 'Protein Xtra Long', category: 'Beauty', price: 20000.00 },
  { name: 'R Strengther', category: 'Beauty', price: 3500.00 },
  { name: 'Rice Mask', category: 'Beauty', price: 1500.00 },
  { name: 'Scalp Advanced', category: 'Beauty', price: 4500.00 },
  { name: 'She Care', category: 'Beauty', price: 3000.00 },
  { name: 'Short Lines/Box', category: 'Beauty', price: 800.00 },
  { name: 'Shoulder Full Color', category: 'Beauty', price: 10000.00 },
  { name: 'Shoulder Highlight', category: 'Beauty', price: 15000.00 },
  { name: 'Silk Press', category: 'Beauty', price: 4000.00 },
  { name: 'Simple Glam', category: 'Beauty', price: 2500.00 },
  { name: 'Simple With Lashes', category: 'Beauty', price: 2000.00 },
  { name: 'Simple Without Lashes', category: 'Beauty', price: 1500.00 },
  { name: 'Soft Glam (Heena)', category: 'Beauty', price: 7000.00 },
  { name: 'Soft Glam (Makeup)', category: 'Beauty', price: 3000.00 },
  { name: 'Stickon/Gel Removal', category: 'Beauty', price: 500.00 },
  { name: 'Stickons', category: 'Beauty', price: 1500.00 },
  { name: 'Styling Cut', category: 'Beauty', price: 3500.00 },
  { name: 'Superb Bridal', category: 'Beauty', price: 13000.00 },
  { name: 'Tips', category: 'Beauty', price: 2000.00 },
  { name: 'Track & Sew Hair Style', category: 'Beauty', price: 5500.00 },
  { name: 'Treasure', category: 'Beauty', price: 3000.00 },
  { name: 'Under Arm', category: 'Beauty', price: 1000.00 },
  { name: 'Undo', category: 'Beauty', price: 100.00 },
  { name: 'Vagacial', category: 'Beauty', price: 3500.00 },
  { name: 'Very Short Full Color', category: 'Beauty', price: 5000.00 },
  { name: 'Volume Lashes', category: 'Beauty', price: 4000.00 },
  { name: 'Wash & Blowdry', category: 'Beauty', price: 800.00 },
  { name: 'Wash & Brush Blowdry', category: 'Beauty', price: 1000.00 },
  { name: 'Wash & Flation', category: 'Beauty', price: 1500.00 },
  { name: 'Wash & Iron Curls', category: 'Beauty', price: 2000.00 },
  { name: 'Wash & Set', category: 'Beauty', price: 1800.00 },
  { name: 'Wash Only', category: 'Beauty', price: 300.00 },
  { name: 'Antiaging', category: 'Clinic', price: 15000.00 },
  { name: 'B12', category: 'Clinic', price: 4500.00 },
  { name: 'Blood Boosting', category: 'Clinic', price: 7000.00 },
  { name: 'D3', category: 'Clinic', price: 5000.00 },
  { name: 'Detoxification', category: 'Clinic', price: 15000.00 },
  { name: 'GFC', category: 'Clinic', price: 25000.00 },
  { name: 'Immune Boosting', category: 'Clinic', price: 15000.00 },
  { name: 'P-Shot', category: 'Clinic', price: 20000.00 },
  { name: 'PRP', category: 'Clinic', price: 10000.00 },
  { name: 'Scalp Analysis', category: 'Clinic', price: 2000.00 },
  { name: 'Scalp Treatment', category: 'Clinic', price: 3500.00 },
  { name: 'Skin & Hair Consultation', category: 'Clinic', price: 2000.00 },
  { name: 'Skin Glow & Brightening', category: 'Clinic', price: 15000.00 },
  { name: 'Steriod Injection', category: 'Clinic', price: 15000.00 },
  { name: 'Acne Treatment', category: 'Facials', price: 7000.00 },
  { name: 'Anti-Aging', category: 'Facials', price: 8000.00 },
  { name: 'Classic', category: 'Facials', price: 6500.00 },
  { name: 'Deep Cleansing', category: 'Facials', price: 3500.00 },
  { name: 'Dermaglow Microneedling', category: 'Facials', price: 15000.00 },
  { name: 'Hydra Glow', category: 'Facials', price: 5500.00 },
  { name: 'Luminous Clarity', category: 'Facials', price: 8000.00 },
  { name: 'Radiance Reveal', category: 'Facials', price: 10000.00 },
  { name: 'Acne Treatment', category: 'SPA', price: 7000.00 },
  { name: 'Anti-Aging Facial', category: 'SPA', price: 8000.00 },
  { name: 'Classic Facial', category: 'SPA', price: 6500.00 },
  { name: 'Classic Mani', category: 'SPA', price: 800.00 },
  { name: 'CLASSIC MANICURE', category: 'SPA', price: 1500.00 },
  { name: 'Classic Pedi', category: 'SPA', price: 1500.00 },
  { name: 'CLASSIC PEDICURE', category: 'SPA', price: 1500.00 },
  { name: 'Classic Skin Ritual', category: 'SPA', price: 7000.00 },
  { name: 'Deep Cleansing', category: 'SPA', price: 3500.00 },
  { name: 'Deep Tissue Massage', category: 'SPA', price: 7000.00 },
  { name: 'Dermaglow Microneedling', category: 'SPA', price: 15000.00 },
  { name: 'Head Massage', category: 'SPA', price: 1000.00 },
  { name: 'Honey Brew Mani', category: 'SPA', price: 1300.00 },
  { name: 'Honey Brew Pedi', category: 'SPA', price: 2000.00 },
  { name: 'Honey Brew Pedi with Hotstone', category: 'SPA', price: 3000.00 },
  { name: 'Hotstone Massage', category: 'SPA', price: 8500.00 },
  { name: 'Hotstone Pedicure', category: 'SPA', price: 2500.00 },
  { name: 'Hydra Glow', category: 'SPA', price: 5500.00 },
  { name: 'Jelly Mani', category: 'SPA', price: 2000.00 },
  { name: 'Jelly Pedi', category: 'SPA', price: 2500.00 },
  { name: 'Jelly Pedi with Hotstone', category: 'SPA', price: 3000.00 },
  { name: 'Luminous Clarity', category: 'SPA', price: 8000.00 },
  { name: 'Paraffin Pedi with Hotstone', category: 'SPA', price: 4000.00 },
  { name: 'Paraffin Pedicure', category: 'SPA', price: 3000.00 },
  { name: 'Pure Polish', category: 'SPA', price: 4500.00 },
  { name: 'Radiance Reveal', category: 'SPA', price: 10000.00 },
  { name: 'Relaxation Massage', category: 'SPA', price: 4000.00 },
  { name: 'Soft Glow Scrub', category: 'SPA', price: 6500.00 },
  { name: 'Steam & Glow', category: 'SPA', price: 7500.00 },
  { name: 'Sultan Retreat', category: 'SPA', price: 15000.00 },
  { name: 'Swedish Massage', category: 'SPA', price: 5500.00 },
  { name: 'The Groom Oasis', category: 'SPA', price: 10000.00 },
  { name: 'Upper Calm Ritual', category: 'SPA', price: 3500.00 },
  { name: 'Velvet Leg Ritual', category: 'SPA', price: 2000.00 },
  { name: 'Velvet Skin Ritual', category: 'SPA', price: 5500.00 },
];

export async function seedRealCatalog() {
  const now = new Date();
  const existingCount = await db.services.count();
  if (existingCount > 0) {
    return { skipped: true, services: 0 };
  }

  await db.transaction("rw", db.services, async () => {
    for (const s of REAL_CATALOG) {
      await db.services.add({
        name: s.name,
        category: s.category,
        price: s.price,
        isActive: true,
        createdAt: now,
        updatedAt: now,
      });
    }
  });

  return { skipped: false, services: REAL_CATALOG.length };
}

// Alias so existing imports of the old function name keep working
// without needing to touch app/setup/page.tsx or app/services/page.tsx.
export const seedStarterCatalog = seedRealCatalog;
